/**************************************************************************
-- -Generated by xSQL SDK for Data Comparison and Synchronization
-- -Date/Time: March 23, 2010 17:59:38

-- -Summary: Synchronization script that makes the content of the database .\SQLEXPRESS.shoprelease 
    the same as the content of the database .\SQLEXPRESS.shoptest.

    BACKUP the database .\SQLEXPRESS.shoprelease before running this script. 

-- -Action:  Execute this script on .\SQLEXPRESS.shoprelease

-- -SQL Server version: 10.0.1600
**************************************************************************/

SET XACT_ABORT ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF


BEGIN TRANSACTION

DECLARE @error INT
DECLARE @ptrBinary varbinary(16)

-- --Table: [dbo].[un_email_templates]
-- --Insert
SET IDENTITY_INSERT [dbo].[un_email_templates] ON
INSERT INTO [dbo].[un_email_templates] ([email_template_id], [name], [subject], [html]) VALUES(2, 'ACTIVATION', 'Activation Code for Simplicity for Business', '<html> 
<head> 
<title>New Simplicity Password</title> 
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
<style type="text/css"> 
<!--
.Body {
	font-family: Verdana, Geneva, sans-serif;
	font-size: 10px;
}
.boby {
	font-size: 12px;
	font-family: Verdana, Geneva, sans-serif;
	text-align: justify;
}
-->
</style> 
</head> 
 
<body bgcolor="#FFFFFF" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"> 
<table width="637" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td width="24" height="45">&nbsp;</td> 
    <td width="613" height="45"> 
      <table width="637" border="3" cellspacing="0" cellpadding="0" bordercolor="#000099" height="68"> 
        <tr> 
          <td> 
            <div align="center"><a href="http://simplicity4business.com"> <img src="##IMAGE_URL##/logo.JPG" alt="##IMAGE_URL##/logo.JPG" width="277" height="83" border="0"></a></div> 
          </td> 
        </tr> 
      </table> 
    </td> 
  </tr> 
</table> 
<table width="644" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td height="18" width="5">&nbsp;</td> 
    <td height="18" width="634"><img src="##IMAGE_URL##/bar1.JPG" alt="##IMAGE_URL##/bar1.JPG" width="639" height="8"></td> 
  </tr> 
</table> 
<table width="639" border="0" cellspacing="0" cellpadding="0" height="112"> 
  <tr> 
    <td width="13" height="56">&nbsp;</td> 
    <td width="626" class="boby"><p>Dear</p> 
      <p>Please find below your Activation Code for  Simplicity for Business.</p> 
      <p>To activate your service you will need to  Logon with:<br> 
        - Your Customer password and User Id -  which are available from your administrator if you have not already received  them, please contact Ultra Nova Coding Ltd, and any email will be sent to the registered  account holder. </p> 
      <p>- Your activation URL:&nbsp; <a href="##URL##">##URL##</a></p> 
      <p> In order to start using NAME OF PRODUCE:<br> 
        - Go to <a href="http://www.simplicity4business.com/">http://www.simplicity4business.com</a> website - and select the &lsquo;Sign Up/ Login&rsquo; button<br> 
        - Enter your Username and Password<br> 
        - Follow the on-screen instructions</p> 
      <p>You will require your Username and Password  each time you logon to use the service, please make sure the chosen password is  memorable and kept secret.</p> 
      <p>You will be prompted to enter your  Activation Code.</p> 
      <p>Additionally, if you wish training please  contact Simplicity for Business at Training@simplicity4business.com</p> 
<p>If you have any queries or concerns, please  telephone the Simplicity Help Desk, this is charged at &pound;1.50 per minute, minimum  of 20 minutes per call. &nbsp;&nbsp;</p> 
    <p>&nbsp;</p></td> 
  </tr> 
  <tr> 
    <td height="56">&nbsp;</td> 
    <td class="boby">&nbsp;</td> 
  </tr> 
</table> 
<table width="10" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td width="10">&nbsp;</td> 
  </tr> 
</table> 
<table width="692" border="0" cellspacing="0" cellpadding="0" > 
  <tr> 
    <td width="14">&nbsp;</td> 
    <td align="right" valign="middle" colspan="2"><font color="#000099" face="Times New Roman, Times, serif" size="2">For 
      more information click <a href="http://simplicity4business.com">here</a> 
      to visit our site</font></td> 
  </tr> 
  <tr> 
    <td colspan="3"><img src="##IMAGE_URL##/Bottom_Swirl.jpg" alt="##IMAGE_URL##/Bottom_Swirl.jpg" ></td></tr>

  <tr> 
    <td width="14">&nbsp;</td> 
    <td width="380"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>E 
      :</b> <a href="mailto:CustomerServices@simplicity4business.com">CustomerServices@simplicity4business.com</a></font></td> 
    <td width="366"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>T:</b> 
      +44 (0) 0207 272 8127 </font></td> 
  </tr> 
  <tr> 
    <td width="14">&nbsp;</td> 
    <td width="380"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>W:</b> 
      <a href="http://www.simplicity4business.com">http://www.simplicity4business.com</a></font></td> 
    <td width="366">&nbsp;</td> 
  </tr> 
</table> 
<table width="696" border="0" cellspacing="0" cellpadding="0" height="85"> 
  <tr> 
    <td width="13" height="94">&nbsp;</td> 
    <td width="751" height="94"> 
      <p><font color="#000000" size="2.5" face="Verdana, Arial, Helvetica, sans-serif">To 
        remove your name from our mailing list, please click <a href="mailto:unsubscribe@simplicity4business.com">here</a>. 
        Questions or comments? E-mail us at tell-me-more@simplicity4business.com 
        or call +44 (0) 0207 272 8127</font></p> 
      </td> 
  </tr> 
</table> 
<table width="697" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td width="12">&nbsp;</td> 
    <td width="685"> 
      <p><font face="Geneva, Arial, Helvetica, san-serif" size="1.5">========================================================================================================================================<br> 
        This e-mail and any attachments are confidential and intended solely for 
        the addressee and may also be privileged or exempt from disclosure under 
        applicable law. If you are not the addressee, or have received this e-mail 
        in error, please notify us by telephone or email (to the numbers or address 
        above) immediately, delete it from your system and do not copy, disclose 
        or otherwise act upon any part of this e-mail or its attachments.<br> 
        <br> 
        Internet communications are not guaranteed to be secure or virus-free.<br> 
        <br> 
        Simplicity for Business does not accept responsibility for any loss arising 
        from unauthorised access to, or interference with, any Internet communications 
        by any third party, or from the transmission of any viruses. Replies to 
        this e-mail may be monitored by Simplicity for Business for operational 
        or business reasons.<br> 
        <br> 
        Any opinion or other information in this e-mail or its attachments that 
        does not relate to the business of the Ultra Nova Coding Ltd is personal 
        to the sender and is not given or endorsed by the Simplicity for Business. 
        Ultra Nova Coding Ltd Registered in England and Wales (registered no. 
        (4235431) Registered Office: SPW Gable House 239 Regents Park Road London 
        N3 3LF Tel: 020 8371 5000 Fax: 020 8346 8588 Registered Address Grenville 
        Workshops 2a Grenville Road London N19 4EH.<br> 
        ========================================================================================================================================</font></p> 
      </td> 
  </tr> 
</table> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
</body> 
</html> ')
INSERT INTO [dbo].[un_email_templates] ([email_template_id], [name], [subject], [html]) VALUES(3, 'PASSWORD', 'New Simplicity Password', '<html> 
<head> 
<title>New Simplicity Password</title> 
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
</head> 
 
<body bgcolor="#FFFFFF" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"> 
<table width="637" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td width="24" height="45">&nbsp;</td> 
    <td width="613" height="45"> 
      <table width="637" border="3" cellspacing="0" cellpadding="0" bordercolor="#000099" height="68"> 
        <tr> 
          <td> 
            <div align="center"><a href="http://simplicity4business.com"> <img src="##IMAGE_URL##/logo.JPG" width="277" height="83" border="0"></a></div> 
          </td> 
        </tr> 
      </table> 
    </td> 
  </tr> 
</table> 
<table width="644" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td height="18" width="5">&nbsp;</td> 
    <td height="18" width="634"><img src="##IMAGE_URL##/bar1.JPG" width="639" height="8"></td> 
  </tr> 
</table> 
<table width="634" border="0" cellspacing="0" cellpadding="0" height="19"> 
  <tr> 
    <td width="94" height="19" align="left" valign="top">&nbsp;</td> 
    <td width="540" valign="bottom"> 
      <div align="right"></div> 
    </td> 
  </tr> 
</table> 
<table width="663" border="0" cellspacing="0" cellpadding="0" height="56"> 
  <tr> 
    <td width="13" height="56">&nbsp;</td> 
    <td width="650"> 
      <p>Dear User</p> 
      <p>        In response to your request  to be reminded of your Simplicity for Business password, please find below your  new password</p> 
      <p><br> 
        Password: ##PASSWORD##</p> 
      <p><br> 
        Thank you</p> 
      <p><br> 
    If you didn''t submit this  request, ignore this email. </p></td> 
  </tr> 
</table> 
<table width="691" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td width="10">&nbsp;</td> 
    <td width="225" align="left" valign="top">&nbsp;</td> 
    <td width="215" align="left" valign="top">&nbsp;</td> 
    <td width="241" align="left" valign="top">&nbsp;</td> 
  </tr> 
</table> 
<table width="692" border="0" cellspacing="0" cellpadding="0" > 
  <tr> 
    <td width="14">&nbsp;</td> 
    <td align="right" valign="middle" colspan="2"><font color="#000099" face="Times New Roman, Times, serif" size="2">For 
      more information click <a href="http://simplicity4business.com">here</a> 
      to visit our site</font></td> 
  </tr> 
  <tr> 
    <td colspan="3"><img src="##IMAGE_URL##/Bottom_Swirl.jpg" alt="##IMAGE_URL##/Bottom_Swirl.jpg" ></td>
  </tr>
  <tr> 
    <td width="14">&nbsp;</td> 
    <td width="380"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>E 
      :</b> <a href="mailto:CustomerServices@simplicity4business.com">CustomerServices@simplicity4business.com</a></font></td> 
    <td width="366"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>T:</b> 
      +44 (0) 0207 272 8127 </font></td> 
  </tr> 
  <tr> 
    <td width="14">&nbsp;</td> 
    <td width="380"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>W:</b> 
      <a href="http://www.simplicity4business.com">http://www.simplicity4business.com</a></font></td> 
    <td width="366">&nbsp;</td> 
  </tr> 
</table> 
<table width="696" border="0" cellspacing="0" cellpadding="0" height="85"> 
  <tr> 
    <td width="13" height="94">&nbsp;</td> 
    <td width="751" height="94"> 
      <p><font color="#000000" size="2.5" face="Verdana, Arial, Helvetica, sans-serif">To 
        remove your name from our mailing list, please click <a href="mailto:unsubscribe@simplicity4business.com">here</a>. 
        Questions or comments? E-mail us at tell-me-more@simplicity4business.com 
        or call +44 (0) 0207 272 8127</font></p> 
      </td> 
  </tr> 
</table> 
<table width="697" border="0" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td width="12">&nbsp;</td> 
    <td width="685"> 
      <p><font face="Geneva, Arial, Helvetica, san-serif" size="1.5">===================================================================================================================<br> 
        This e-mail and any attachments are confidential and intended solely for 
        the addressee and may also be privileged or exempt from disclosure under 
        applicable law. If you are not the addressee, or have received this e-mail 
        in error, please notify us by telephone or email (to the numbers or address 
        above) immediately, delete it from your system and do not copy, disclose 
        or otherwise act upon any part of this e-mail or its attachments.<br> 
        <br> 
        Internet communications are not guaranteed to be secure or virus-free.<br> 
        <br> 
        Simplicity for Business does not accept responsibility for any loss arising 
        from unauthorised access to, or interference with, any Internet communications 
        by any third party, or from the transmission of any viruses. Replies to 
        this e-mail may be monitored by Simplicity for Business for operational 
        or business reasons.<br> 
        <br> 
        Any opinion or other information in this e-mail or its attachments that 
        does not relate to the business of the Ultra Nova Coding Ltd is personal 
        to the sender and is not given or endorsed by the Simplicity for Business. 
        Ultra Nova Coding Ltd Registered in England and Wales (registered no. 
        (4235431) Registered Office: SPW Gable House 239 Regents Park Road London 
        N3 3LF Tel: 020 8371 5000 Fax: 020 8346 8588 Registered Address Grenville 
        Workshops 2a Grenville Road London N19 4EH.<br> 
        ==================================================================================================================</font></p> 
      </td> 
  </tr> 
</table> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
</body> 
</html> ')

SET IDENTITY_INSERT [dbo].[un_email_templates] OFF


COMMIT TRANSACTION

