/**************************************************************************
-- -Generated by xSQL SDK for Data Comparison and Synchronization
-- -Date/Time: March 13, 2010 23:56:12

-- -Summary: Synchronization script that makes the content of the database .\SQLEXPRESS.ShoppingTrolleyRelease 
    the same as the content of the database .\SQLEXPRESS.ShoppingTrolley.

    BACKUP the database .\SQLEXPRESS.ShoppingTrolleyRelease before running this script. 

-- -Action:  Execute this script on .\SQLEXPRESS.ShoppingTrolleyRelease

-- -SQL Server version: 10.0.1600
**************************************************************************/

SET XACT_ABORT ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF


BEGIN TRANSACTION

DECLARE @error INT
DECLARE @ptrBinary varbinary(16)

-- --Table: [dbo].[un_settings]
-- --Insert
SET IDENTITY_INSERT [dbo].[un_settings] ON
INSERT INTO [dbo].[un_settings] ([setting_id], [setting_group], [setting_key], [setting_value]) VALUES(1, 'ViewDemo', 'EmailSubject', 'Simplicity4Business Thank you')
INSERT INTO [dbo].[un_settings] ([setting_id], [setting_group], [setting_key], [setting_value]) VALUES(2, 'ViewDemo', 'EmailContents', 'Thankyou')

SET IDENTITY_INSERT [dbo].[un_settings] OFF


COMMIT TRANSACTION

